Repository DSC-UNSRI/cs-api, pull requests merged in 2021-06, with the labels that each got.

#14 jest installation and configuration for testing
  .eslintrc.json
  README.md
  __test__/exampleTest.test.js
  jest.config.js
  package-lock.json
  package.json
Labels: enhancement

#15 added client error and server error exception
  src/exceptions/Client Error.js
  src/exceptions/ServerError.js
Labels: enhancement

#17 Add base server architecture
  package.json
  src/api/event/handler.js
  src/api/event/index.js
  src/api/event/routes.js
  src/exceptions/ClientError.js
  src/server.js
  src/validator/event/index.js
Labels: enhancement

#21 Mengubah file example env
  .example.env
  package.json
Labels: documentation

#23 added events handlers base
  src/api/event/handler.js
Labels: enhancement

#24 Update Main Branch
  .eslintrc.json
  .example.env
  README.md
  __test__/exampleTest.test.js
  jest.config.js
  package-lock.json
  package.json
  src/api/event/handler.js
  src/api/event/index.js
  src/api/event/routes.js
  src/exceptions/ClientError.js
  src/exceptions/ServerError.js
  src/server.js
  src/validator/event/index.js
Labels: documentation, enhancement

#25 Update table event
  migrations/1623506971374_create-table-events.js
  migrations/1624112563451_create-table-authentication.js
Labels: enhancement

#28 Create table ormawa
  migrations/1624194679673_create-table-ormawa.js
Labels: enhancement

#31 Added Event Service
  .example.env
  package-lock.json
  package.json
  src/api/auth/index.js
  src/api/event/handler.js
  src/api/event/index.js
  src/server.js
  src/services/postgres/EventService.js
  src/validator/event/index.js
Labels: enhancement

#32 added constraints on ormawa and event table
  migrations/1624194679673_create-table-ormawa.js
  migrations/1624354303441_add-constraint-to-tables.js
Labels: enhancement

#34 OrmawaAPI+validator && pluginnya ke server.js
  package-lock.json
  src/api/ormawa/handler.js
  src/api/ormawa/index.js
  src/api/ormawa/routes.js
  src/server.js
  src/services/postgres/OrmawaService.js
  src/validator/ormawa/index.js
Labels: enhancement

#35 JWT Authentication System & Ormawa Service
  .example.env
  package-lock.json
  package.json
  src/api/auth/handler.js
  src/api/auth/index.js
  src/api/event/handler.js
  src/api/event/routes.js
  src/api/ormawa/handler.js
  src/exceptions/ClientError.js
  src/server.js
  src/services/postgres/AuthService.js
  src/services/postgres/EventService.js
  src/services/postgres/OrmawaService.js
  src/tokenmanager/index.js
  src/validator/auth/index.js
Labels: enhancement

#37 [Testing] Add endpoint tests
  __test__/endpoints/auth/loginTest.test.js
  __test__/endpoints/events/createEventTest.test.js
  __test__/endpoints/events/readEventTest.test.js
  __test__/endpoints/events/readEventsTest.test.js
  __test__/endpoints/ormawa/createOrmawaTest.test.js
  package-lock.json
  package.json
Labels: enhancement

#40 fix JWT payload
  src/api/auth/handler.js
  src/server.js
Labels: bug

#41 [Docs] Update README.md
  README.md
  dev/DSC CS-API.postman_environment.json
  dev/DSC.postman_collection.json
Labels: documentation

#43 added event authorization, add error messages, add map db to models
  src/api/event/handler.js
  src/services/postgres/AuthService.js
  src/services/postgres/EventService.js
  src/services/postgres/OrmawaService.js
  src/tokenmanager/index.js
  src/utils/DBtoModel.js
Labels: bug, enhancement

#44 Update and fix Jest Test
  __test__/apiTest.test.js
  __test__/endpoints/auth/loginTest.test.js
  __test__/endpoints/events/createEventTest.test.js
  __test__/endpoints/events/readEventTest.test.js
  __test__/endpoints/events/readEventsTest.test.js
  __test__/endpoints/ormawa/createOrmawaTest.test.js
  __test__/exampleTest.test.js
Labels: bug, enhancement

#45 Add auth refresh, logout and event update, delete test
  __test__/apiTest.test.js
Labels: enhancement

#51 change postman api docs
  README.md
Labels: documentation

#54 added redis, search event query, owner auth
  .example.env
  README.md
  __test__/apiTest.test.js
  dev/generateownerauth.js
  package-lock.json
  package.json
  src/api/event/handler.js
  src/api/ormawa/routes.js
  src/server.js
  src/services/postgres/EventService.js
  src/services/redis/CacheService.js
Labels: enhancement

#56 Firebase Storage Static File Upload Feature
  .example.env
  .gitignore
  __test__/apiTest.test.js
  __test__/testimg.jpg
  dev/generateownerauth.js
  package-lock.json
  package.json
  src/api/upload/handler.js
  src/api/upload/index.js
  src/api/upload/routes.js
  src/server.js
  src/services/firebase/AdminService.js
  src/services/firebase/StorageService.js
  src/validator/upload/index.js
Labels: enhancement

#58 fix bucket naming
  src/services/firebase/StorageService.js
Labels: bug
